[TOC]

异常处理
====

##**什么是异常？**

	异常是错误发生的信号，一旦程序出错，就会产生一个异常，应用程序未处理该异常
	异常边会抛出，程序随之终止
##**常见的异常类型**

###语法错误

	应该在程序运行前修正
```
if 1 > 2:
    pass('xxx') #SyntaxError: invalid syntax
```
###逻辑错误

```
x  #NameError: name 'x' is not defined

l=[]
l[2]  #IndexError: list index out of range

class Foo:
    pass
Foo.s   #AttributeError: type object 'Foo' has no attribute 's'

k={'x':1}
k['1']   #KeyError: '1'

1/0  #ZeroDivisionError: division by zero

for i in 3:  #TypeError: 'int' object is not iterable
    pass

age=input('>>')
age=int(age)   #ValueError: invalid literal for int() with base 10: 'as'
```
##**如何处理异常**

###try的使用

```python
try:...except xxxError:
try:...except xxxError as e: print(e)  #打印报错内容
try:...except xxxError as e: print(e)  else: print('没有异常才触发')
try:...finally: print('有没有异常都触发')
```
```python
print('====>start<====')
try:
    l=[]
    # print(l[1])
    print('====>1')
    d={}
    # d['2']
    print('====>2')
except IndexError as e:
    print('====>',e)
except KeyError as e:   #可以像elif一样可以写多个匹配
    print('====>',e)
except Exception as e:   #万能异常处理方式Exception
    print('万能异常',e)
else:
    print('没有异常发生的时候触发')
finally:    #有没有异常都触发的一个方法
    print('有没有异常都触发')
print('=====>end<=====')

#finally的使用
try:
    conn=connect('1.1.1.1',3306)
    conn.execute('select * from t1;')
finally:   #自动回收系统资源
    conn.close()
```
###raise 和assert的使用

```python
#主动抛出一个异常
stus=['egon','lqx']
ip_list=[
    '1.1.1.1:8080',
    '2.2.2.2:8090'
]
if len(ip_list) ==0:
    raise TypeError   #主动抛出一个异常
assert len(ip_list)  >0    #条件必须成立，否则抛出一个异常：assert len(ip_list)  >0   AssertionError
print('从ip_list取出ip地址，验证可用性')
```
##**自定义异常**

```python
自定义一个异常：必须要先继承python自带的异常处理class
```
```python
#自定义一个异常：必须要先继承python自带的异常处理class
class MyException(BaseException):
    def __init__(self,msg):
        super(MyException,self).__init__()   #调用父类的初始化方法
        self.msg=msg
raise MyException('类型出错')  #异常的值
'''
Traceback (most recent call last):
  File "D:/python20期课程/day8/1、异常处理.py", line 132, in <module>
    raise MyException('类型出错')  #异常的值
__main__.MyException          #不加__str__打印出来的是一个对象
'''

class MyException(BaseException):
    def __init__(self,msg):
        super(MyException,self).__init__()   #调用父类的初始化方法
        self.msg=msg
    def __str__(self):   #加上__str__会在执行类的时候主动返回__str__的return的结果，__str__返回值必须是一个str类型
        return '<%s>' %self.msg
raise MyException('类型出错')  #异常的值
'''
Traceback (most recent call last):
  File "D:/python20期课程/day8/1、异常处理.py", line 144, in <module>
    raise MyException('类型出错')  #异常的值
__main__.MyException: <类型出错>    #加上__str__打印出来的是对象的值
'''
```